### ISSUE TITLE
No upload button

### ISSUE THREAD

**Issue by kariellen35** [jaredatch/Basic-User-Avatars#24]
The option to upload an avatar is not there. I tried disabling all plugins except bbpress and switching to twenty fifteen. Still only see "browse" button when adding a local file. It will upload when I hit enter but I'm worried some users won't know to do that. Just wondering if this is how it was written or if it's an issue with the new version of wordpress.

Thank you for your time!

Take care,
Kari

**Comment by andrewlimaza** [comment]
Hi @kariellen35 

I'm sorry to hear about this, I have recently started maintaining and contributing to this project. I know this issue is really old, if you are still experiencing this issue please let us know by creating a new support topic on - https://wordpress.org/plugins/basic-user-avatars/

A new update will be released in the near future.
