### ISSUE TITLE
Mixed content on https page. Avatar opload images comes from http

### ISSUE THREAD

**Issue by openui54u** [jaredatch/Basic-User-Avatars#28]
While being logged-in into bbPress I found out that images from (my) avatar is loaded via http. Thus giving a message warning in console concerning the mixed content.
Could it be that the mixed images (avatars) upload has to do with any settings in your plugin?
Regards
Edwin

**Comment by andrewlimaza** [comment]
Hi Edwin,

Thank you for reaching out, I have recently started contributing to and maintaining this plugin. This should be fixed in an upcoming release.

For the time being you may download the pre-release here (master) - https://github.com/jaredatch/Basic-User-Avatars

I am going to close this issue, but if you are still experiencing this issue please feel free to open a new issue/report on this repo.
