### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by erikandershed** [jaredatch/Basic-User-Avatars#5]
Hi, I am using the plugin Social Login (https://wordpress.org/plugins/oa-social-login/), I think this is the problem. But when I save the profile the avatar is not updated its still the social avatar. Please help

**Comment by erikandershed** [comment]
Just checked, I cant get it to work even on a user that don't have an social avatar

**Comment by jaredatch** [comment]
@erikandershed sorry to hear you are having issues with the plugin.

More than likely the issue is due to a theme or plugin conflict. Can you please temporarily (for testing) switch you theme to TwentyFifteen and deactivate all other plugins and try again? Typically this will fix the issue, which will then allow you to start turning things on one by one to identify the culprit.

If you switch themes and turn off the plugins and you are still having issues let me know.
